### ISSUE TITLE
خطا در خروجی

### ISSUE THREAD

**Issue by roozbeh10** [miladesign/Vinoos-bugs#1]
سلام آقا میلاد
Dependencies طبقه آموزش که دادید پیش رفتم و همه پیش نیاز ها رو نصب کردم و در قسمت
  :همه نرم افزار ها نصب شد  .ولی در زمان خروجی پروژه همچین خطایی داد
![error](https://user-images.githubusercontent.com/30473662/43666998-1231a0c4-972b-11e8-90f9-b5ed08d05f3e.png)
لطفا بگید که اشکال از کجاست؟

**Comment by miladesign** [comment]
سلام
لطفا متن کامل خطا رو ارسال کنید.
نسخه کوردوایی که نصب کردید چنده؟

**Comment by roozbeh10** [comment]
*
********** BUILD STARTED AT 2018/08/03 23:56:17 **********
*

Removing platform android from config.xml file...


Using cordova-fetch for cordova-android@C:\Program Files (x86)\Vinoos\Data\platforms\6.2.3.tgz
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms\android
	Package: com.example.c1531299628406
	Name: Vinoos
	Activity: MainActivity
	Android target: android-25
Subproject Path: CordovaLib
Android project created with cordova-android@6.2.3
(node:5592) UnhandledPromiseRejectionWarning: TypeError: prepare.preparePlatforms is not a function
    at C:\Users\R\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\platform.js:197:40
    at _fulfilled (C:\Users\R\Documents\Vinoos\Projects\tesm\node_modules\cordova-android\node_modules\q\q.js:854:54)
    at C:\Users\R\Documents\Vinoos\Projects\tesm\node_modules\cordova-android\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Users\R\Documents\Vinoos\Projects\tesm\node_modules\cordova-android\node_modules\q\q.js:816:13)
    at C:\Users\R\Documents\Vinoos\Projects\tesm\node_modules\cordova-android\node_modules\q\q.js:624:44
    at runSingle (C:\Users\R\Documents\Vinoos\Projects\tesm\node_modules\cordova-android\node_modules\q\q.js:137:13)
    at flush (C:\Users\R\Documents\Vinoos\Projects\tesm\node_modules\cordova-android\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:5592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


ورژن کوردا هم 8.0.0

**Comment by miladesign** [comment]
کوردوا رو پاک کنید و نسخه 6.5.0 رو نصب کنید تا مشکل برطرف بشه.
راهنمای نصب نسخه 6.5.0 کوردوا توی لینک زیر قرار داره:
[http://vinoos.ir/help/install_cordova.php](http://vinoos.ir/help/install_cordova.php)
