### ISSUE TITLE
یک ارور در خروجی

### ISSUE THREAD

**Issue by pedramon08djv** [miladesign/Vinoos-bugs#13]
سلام 
ارور زیر میده
فیلترشکن موقع خروجی روشن هست 
برنامه های پیش نیاز نصب شده
نسخه دیباگ و نهایی تست شد
همه یو اس پی ها و دوتای دیگه تست شده 
کوردوا 6.2.3 
خروجی کانواس پلاس
ویندوز سون 64

`
*
********** BUILD STARTED AT 2019/02/28 08:47:38 **********
*

Removing platform android from config.xml file...

Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms\android
	Package: com.gpars.char
	Name: ch
	Activity: MainActivity
	Android target: android-25
Subproject Path: CordovaLib
Android project created with cordova-android@6.2.3
--save flag or autosave detected
Saving android@C:\Vinoos\Data\platforms\6.2.3.tgz into config.xml file ...

ANDROID_HOME=C:\AndroidSDK
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_172
:wrapper

BUILD SUCCESSFUL

Total time: 6.047 secs
Picked up _JAVA_OPTIONS: -Xmx2g
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_1q9vqdvuhj05ozb20my6nlql3.run(C:\Users\pedram\Documents\Vinoos\Projects\chh\platforms\android\build.gradle:137)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
The ProjectDependency.getProjectConfiguration() method has been deprecated and is scheduled to be removed in Gradle 4.0.
ModuleDependency.getConfiguration() has been deprecated and is scheduled to be removed in Gradle 4.0. Use ModuleDependency.getTargetConfiguration() instead.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
:CordovaLib:processDebugJavaRes UP-TO-DATE
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:prepareOrgApacheCordovaCordovaLib623DebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:incrementalDebugJavaCompilationSafeguard
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
C:\Users\pedram\Documents\Vinoos\Projects\chh\platforms\android\src\com\gpars\char\MainActivity.java:20: error: <identifier> expected
:compileDebugJavaWithJavac FAILED
package com.gpars.char;

                  ^
BUILD FAILED
C:\Users\pedram\Documents\Vinoos\Projects\chh\platforms\android\build\generated\source\r\debug\com\gpars\char\R.java:8: error: <identifier> expected

package com.gpars.char;
Total time: 7.939 secs
                  ^
C:\Users\pedram\Documents\Vinoos\Projects\chh\platforms\android\build\generated\source\buildConfig\debug\com\gpars\char\BuildConfig.java:4: error: <identifier> expected
package com.gpars.char;
                  ^
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Users\pedram\Documents\Vinoos\Projects\chh\platforms\android\src\com\gpars\char\MainActivity.java:20: error: <identifier> expected

package com.gpars.char;
                  ^
C:\Users\pedram\Documents\Vinoos\Projects\chh\platforms\android\build\generated\source\r\debug\com\gpars\char\R.java:8: error: <identifier> expected
package com.gpars.char;
                  ^
C:\Users\pedram\Documents\Vinoos\Projects\chh\platforms\android\build\generated\source\buildConfig\debug\com\gpars\char\BuildConfig.java:4: error: <identifier> expected
package com.gpars.char;
                  ^
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Picked up _JAVA_OPTIONS: -Xmx2g

`

**Comment by miladesign** [comment]
<div dir=rtl>این خطا بخاطر استفاده از کلمه char در پکیج نیم پروژه هست که از کلمات پیش فرض توی جاوا هستش.</div>
