### ISSUE TITLE
ارور پس از خروجی

### ISSUE THREAD

**Issue by MagryTM** [miladesign/Vinoos-bugs#22]
بابت این ارور رفتم یه پک اس دی کی دیگه هم دانلود کردم چون گفتم شاید مشکل از اس دی کی منه...

* What went wrong:
Execution failed for task ':app:compileReleaseAidl'.
> java.io.IOException: com.android.ide.common.process.ProcessException: Error while executing process O:\Magry TM\SDK Android\Android SDK\build-tools\29.0.0\aidl.exe with arguments {-pO:\Magry TM\SDK Android\Android SDK\platforms\android-28\framework.aidl -oC:\Users\mahdi\Documents\Vinoos\Projects\Proud\platforms\android\app\build\generated\aidl_source_output_dir\release\compileReleaseAidl\out -IC:\Users\mahdi\Documents\Vinoos\Projects\Proud\platforms\android\app\src\main\aidl -IC:\Users\mahdi\Documents\Vinoos\Projects\Proud\platforms\android\app\src\release\aidl -IC:\Users\mahdi\Documents\Vinoos\Projects\Proud\platforms\android\CordovaLib\build\intermediates\aidl_parcelable\release\compileReleaseAidl\out -dC:\Users\mahdi\AppData\Local\Temp\aidl1813616994770796758.d C:\Users\mahdi\Documents\Vinoos\Projects\Proud\platforms\android\app\src\main\aidl\com\android\vending\billing\IInAppBillingService.aidl}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

مشکل از چیه؟

**Comment by miladesign** [comment]
<div dir=rtl>سلام. از چه پلاگینایی استفاده کردین؟</div>
