### ISSUE TITLE
سلام یک مشکل جدید در ویندوز 10 هست 

### ISSUE THREAD

**Issue by mohsensd1373** [miladesign/Vinoos-bugs#5]
درود و سلام بر طراح گرامی 
مشکلی در ویندوز  10 بهش برخورد عدم نمایش پروژه های سیو شده در مای داکیومنت است 
البته شروع برنامه هم این ارور رو میده 
![image](https://user-images.githubusercontent.com/6122962/43967635-0f5764d8-9cda-11e8-95c1-87eb483fac7d.png)

باتشکر از زحمات شما در این برنامه 
من صاحب سایت 
gm3.ir 
هستم اگر خواستید به رایگان نرم افزار ونوس را در سایتم تبلیغ می کنم 
البته با ایمیل من تماس بگیرید 
mohsensd1373@gmail.com

**Comment by miladesign** [comment]
<div dir=rtl>سلام</div><br><div dir=rtl>برنامه با ویندوز 10 مشکلی نداره چون خودم از ویندوز 10 استفاده میکنم. به آدرس گفته شده برید ببینید فایل موردنظر وجود داره یا نه</div>

**Comment by mohsensd1373** [comment]
سلام 
اگر دقت کرده باشید
nightwolf 
اسم سیستم شما باید باشه 
که برنامه می خواد یک آیکن رو از درایو ویندوز و از  حساب کاربری گرگ شب  در پروژه ونوس دریافت کنه 
در سیستم من نه چنین کاربری وجود داره نه چنین فایلی 
پس ربطی به ویندوز من نداره 
پس شما باید داخل کد های خودتون ببینید که این فایل رو برای چی دریافت میکنید 
باتشکر ازشما

**Comment by miladesign** [comment]
<div dir=rtl>بله درسته. مشکل توی فایل نصبی بود یه فایلی اشتباهی واردش شده که فایل جدید رو جایگزین می کنم.<br>شما <a href=http://bayanbox.ir/info/8162847911025447371/database>این فایل</a> رو جایگزین فایلی با همین اسم توی محل نصب وینوس کنید.</div>

**Comment by mohsensd1373** [comment]
بله .. احسنت و تشکر هم مشکل ارور اولیه حل شد هم عدم نمایش پروژه 
باتشکر 
انشاالله موفق و موید باشید
