### ISSUE TITLE
شناخت پیشنیازها

### ISSUE THREAD

**Issue by omidamitis** [miladesign/Vinoos-bugs#6]
سلام آقا میلاد
من پیش نیازهارو طبق راهنمای خودتون نصب کردم ولی وینوس نمیشناسه
ویندوزم 8.1 و 64بیتی

**Comment by miladesign** [comment]
<div dir=rtl>سلام<br>اگه مطمئنید درست نصب شدن می تونید تیک گزینه "عدم بررسی پیش نیازها" رو از تنظیمات فعال کنید.</div>

**Comment by omidamitis** [comment]
ممنون

**Comment by omidamitis** [comment]
سلام آقا میلاد نشد موقع نصب پلاگین ها میگه کوردوا نصب نیست

**Comment by miladesign** [comment]
<div dir=rtl>این خطا رو مقعی میده که کوردوا نصب نباشه. بررسی کنید ببینید نصب هست یا نه</div>
