### ISSUE TITLE
خروجی عمودی و افقی

### ISSUE THREAD

**Issue by mohamaad123** [miladesign/Vinoos-bugs#7]
سلام دوست عزیز اول ممنون وخسته نباشید بابت نرم افزاری که ساختی
بازی هایی که افقی هستند رو تیک افقی رو می زنم ولی عمودی و کوچیک خروجی میگیره با سه نوع خروجی هم امتحان کردم فرقی نکرد

**Comment by miladesign** [comment]
<div dir="rtl>سلام. میتونید فایل زبان برنامه رو ویرایش کنید و جای افقی عمودی رو عوض کنید.</div>
