### ISSUE TITLE
مشکل د رخروجی

### ISSUE THREAD

**Issue by hamed1987** [miladesign/Vinoos-bugs#9]
*
********** BUILD STARTED AT 2018/09/24 19:31:10 **********
*

You have been opted out of telemetry. To change this, run: cordova telemetry on.

You have been opted out of telemetry. To change this, run: cordova telemetry on.
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms\android
	Package: com.skinpacks.colorbox
	Name: Color_Box
	Activity: MainActivity
	Android target: android-25
Subproject Path: CordovaLib
Android project created with cordova-android@6.2.3
Installing "vinoos-canvasplus" for android
Failed to install 'vinoos-canvasplus':Error: cmd: Command failed with exit code ENOENT
Error: cmd: Command failed with exit code ENOENT
    at ChildProcess.whenDone (C:\Users\hamed\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)

    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by miladesign** [comment]
<div dir=rtl>سلام<br>لطفا نسخه کوردوای نصب شده رو چک کنید و بگید چنده</div>

**Comment by hamed1987** [comment]
> سلام
> لطفا نسخه کوردوای نصب شده رو چک کنید و بگید چنده

Microsoft Windows [Version 10.0.17134.285]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\hamed>cordova --version
? May Cordova anonymously report usage statistics to improve the tool over time? Yes

Thanks for opting into telemetry to help us improve cordova.
6.5.0


┌──────────────────────────────────────────┐
│ Update available: 8.0.0 (current: 6.5.0) │
│ Run npm install -g cordova to update.    │
└──────────────────────────────────────────┘


C:\Users\hamed>

**Comment by miladesign** [comment]
<div dir=rtl>میشه بگید چه مراحلی انجام میدید که به این خطا میرسید؟<br>و نسخه های نصب شده پیش نیازها رو ارسال کنید چک کنم</div>

**Comment by hamed1987** [comment]
> میشه بگید چه مراحلی انجام میدید که به این خطا میرسید؟
> و نسخه های نصب شده پیش نیازها رو ارسال کنید چک کنم

اون مشکلو خودم حل کردم
الان یک مشکل دیگه دارم 
من تو بازیم از ادمب و گوگل پلی گیم سرویس استفاده کردم
وقتی میخوام پلاگین پوشه رو استفاده کنم تو خروجی به مشکل میخوره و تو گوگل پلی گیم سرویس تداخل داره 
راه حلی واسش ندارین؟
اینا لیست پلاگیناس:
https://dl.skinpacks.com/dl/1.jpg
اینم خطا:
:processReleaseResources FAILED


FAILURE: Build failed with an exception.
BUILD FAILED


* What went wrong:
Total time: 37.598 secs
Execution failed for task ':processReleaseResources'.
> Error: more than one library with package name 'com.google.android.gms'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: cmd: Command failed with exit code 1 Error output:

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> Error: more than one library with package name 'com.google.android.gms'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by miladesign** [comment]
<div dir=rtl>واسه این کار باید گیتهاب پلاگین ها رو دستکاری کنید.</div>

**Comment by hamed1987** [comment]
میشه بگین چیو و از کجا تغییر بدم چون واقعا لازم دارم
